[settings]
always_keep_download = true
disable_hints = ["registry", "outdated_bump"]
experimental = true
plugin_autoupdate_last_check_duration = "0"
use_versions_host = false

[tools]
bazel = ["8.3"]
bun = ["1"]
java = ["temurin-21"]
maven = ["3.9"]
# Also installing 22.14.0 because that's the version used at Dremio.
# https://github.com/parteincerta/dremio/blob/master/.nvmrc
node = ["22", "22.14.0"]
